import pg from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { santaListings } from "./schema";

const { Pool } = pg;

async function seed() {
  if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL required");
  }

  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const db = drizzle(pool);

  const sampleSantas = [
    {
      slug: "father-christmas-nicholas",
      name: "Nicholas Evergreen",
      headline: "Traditional Real Beard Father Christmas",
      type: "both",
      bio: "With over 15 years of professional experience, Nicholas brings the true magic of Christmas to every appearance. His natural full white beard and warm, gentle manner have made him one of the most sought-after Father Christmas performers in the South East. Nicholas specialises in creating authentic, memorable experiences for children and families alike, whether it's an intimate home visit or a grand grotto experience.",
      experience: "15+ years professional experience. Featured in local press and TV appearances. Former department store Santa at Harrods. Trained in child safeguarding and first aid.",
      services: ["Home Visits", "Grotto Experiences", "Corporate Events", "Shopping Centre Appearances", "Video Calls"],
      location: "London",
      region: "South East",
      profileImageUrl: "https://images.unsplash.com/photo-1603793303277-ed67787545e5?w=600&fit=crop&q=80",
      galleryImages: [
        "https://images.unsplash.com/photo-1639264128236-78064efff737?w=800&fit=crop&q=80",
        "https://images.unsplash.com/photo-1543893419-fcc585654853?w=800&fit=crop&q=80",
      ],
      youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      socialLinks: { instagram: "https://instagram.com", website: "https://example.com" },
      pricingFrom: "£350",
      availableDates: "November - December",
      contactEmail: "nicholas@example.com",
      dbsChecked: true,
      realBeard: true,
      homeVisits: true,
      corporateEvents: true,
      schoolsNurseries: true,
      grottos: true,
      approved: true,
      featured: true,
    },
    {
      slug: "santa-james-corporate",
      name: "James Whitfield",
      headline: "Corporate & Events Santa Specialist",
      type: "lookalike",
      bio: "James is a professional corporate Santa who brings festive cheer to office parties, product launches, and brand activations across the Midlands and beyond. With a background in entertainment and events management, James understands the importance of professionalism and brand alignment. He's worked with major retailers, FTSE 100 companies, and prestigious venues.",
      experience: "10 years in corporate entertainment. Clients include John Lewis, Selfridges, and Sky. Fully insured and DBS checked. Available for UK-wide travel.",
      services: ["Corporate Events", "Brand Activations", "Product Launches", "Office Parties", "Charity Events"],
      location: "Birmingham",
      region: "West Midlands",
      profileImageUrl: "https://images.unsplash.com/photo-1511600173735-a896042389cf?w=600&fit=crop&q=80",
      galleryImages: [
        "https://images.unsplash.com/photo-1603793303277-ed67787545e5?w=800&fit=crop&q=80",
        "https://images.unsplash.com/photo-1639264128236-78064efff737?w=800&fit=crop&q=80",
      ],
      socialLinks: { website: "https://example.com", facebook: "https://facebook.com" },
      pricingFrom: "£500",
      availableDates: "October - January",
      contactEmail: "james@example.com",
      dbsChecked: true,
      realBeard: false,
      homeVisits: false,
      corporateEvents: true,
      schoolsNurseries: false,
      grottos: true,
      approved: true,
      featured: true,
    },
    {
      slug: "storytelling-santa-peter",
      name: "Peter Hollybrook",
      headline: "Storytelling Santa & Children's Entertainer",
      type: "both",
      bio: "Peter is a classically trained actor who brings Father Christmas to life through the art of storytelling. Each visit includes personalised stories, interactive activities, and genuine magical moments that children remember for years. Peter's warm, engaging style is perfect for intimate settings where quality of experience matters most.",
      experience: "8 years as a professional Santa performer. Trained actor (RADA). Published children's author. Enhanced DBS checked. Paediatric first aid certified.",
      services: ["Home Visits", "School Visits", "Nursery Visits", "Library Events", "Private Parties", "Storytelling Sessions"],
      location: "Oxford",
      region: "South East",
      profileImageUrl: "https://images.unsplash.com/photo-1651097681165-f8f6f2c37134?w=600&fit=crop&q=80",
      galleryImages: [
        "https://images.unsplash.com/photo-1543893419-fcc585654853?w=800&fit=crop&q=80",
        "https://images.unsplash.com/photo-1762678589475-eb4000185c0d?w=800&fit=crop&q=80",
      ],
      socialLinks: { instagram: "https://instagram.com" },
      pricingFrom: "£250",
      availableDates: "November - December",
      contactEmail: "peter@example.com",
      dbsChecked: true,
      realBeard: true,
      homeVisits: true,
      corporateEvents: false,
      schoolsNurseries: true,
      grottos: false,
      approved: true,
      featured: false,
    },
    {
      slug: "school-santa-margaret",
      name: "Margaret Frost",
      headline: "Mrs Claus & School Visit Specialist",
      type: "lookalike",
      bio: "Margaret brings the warmth of Mrs Claus to schools, nurseries, and community events across Yorkshire. With 20 years of experience working with children as a former primary school headteacher, Margaret creates safe, inclusive, and wonderfully festive experiences. She offers both Mrs Claus appearances and joint bookings with her partner Santa.",
      experience: "Former primary school headteacher. 12 years as professional Mrs Claus. Enhanced DBS checked. SEND awareness trained. First aid certified.",
      services: ["School Visits", "Nursery Visits", "Community Events", "Care Home Visits", "Joint Santa & Mrs Claus Bookings"],
      location: "Leeds",
      region: "Yorkshire",
      profileImageUrl: "https://images.unsplash.com/photo-1762678589475-eb4000185c0d?w=600&fit=crop&q=80",
      galleryImages: [
        "https://images.unsplash.com/photo-1762678589475-eb4000185c0d?w=800&fit=crop&q=80",
        "https://images.unsplash.com/photo-1511600173735-a896042389cf?w=800&fit=crop&q=80",
      ],
      socialLinks: { facebook: "https://facebook.com" },
      pricingFrom: "£200",
      availableDates: "November - December",
      contactEmail: "margaret@example.com",
      dbsChecked: true,
      realBeard: false,
      homeVisits: true,
      corporateEvents: false,
      schoolsNurseries: true,
      grottos: false,
      approved: true,
      featured: false,
    },
    {
      slug: "luxury-grotto-santa-richard",
      name: "Richard Kingswood",
      headline: "Luxury Grotto & Premium Event Santa",
      type: "both",
      bio: "Richard is known for his impeccable attention to detail and premium presentation. He provides the complete luxury grotto experience, from bespoke costumes and handcrafted props to personalised gift wrapping. Richard works exclusively with premium venues, luxury brands, and discerning families who want nothing but the very best Father Christmas experience.",
      experience: "12 years as a professional luxury Santa. Clients include Fortnum & Mason, The Savoy, and Soho Farmhouse. Custom-made costumes by theatrical costumiers. Fully insured with £10M public liability.",
      services: ["Luxury Grottos", "Premium Home Visits", "Five-Star Hotel Events", "High-End Brand Events", "VIP Experiences"],
      location: "London",
      region: "South East",
      profileImageUrl: "https://images.unsplash.com/photo-1639264128236-78064efff737?w=600&fit=crop&q=80",
      galleryImages: [
        "https://images.unsplash.com/photo-1603793303277-ed67787545e5?w=800&fit=crop&q=80",
        "https://images.unsplash.com/photo-1511600173735-a896042389cf?w=800&fit=crop&q=80",
        "https://images.unsplash.com/photo-1543893419-fcc585654853?w=800&fit=crop&q=80",
      ],
      youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      socialLinks: { website: "https://example.com", instagram: "https://instagram.com" },
      pricingFrom: "£800",
      availableDates: "November - December (limited availability)",
      contactEmail: "richard@example.com",
      dbsChecked: true,
      realBeard: true,
      homeVisits: true,
      corporateEvents: true,
      schoolsNurseries: false,
      grottos: true,
      approved: true,
      featured: true,
    },
    {
      slug: "media-santa-david",
      name: "David Winterbourne",
      headline: "Media & TV Santa Performer",
      type: "both",
      bio: "David is one of the UK's most recognisable professional Santas, with credits spanning television, film, and national advertising campaigns. His commanding presence, authentic look, and professional training make him the go-to choice for productions requiring a truly believable Father Christmas. David is equally comfortable in front of a camera as he is in a packed grotto.",
      experience: "Featured in ITV Christmas specials, BBC Children in Need, and Marks & Spencer campaigns. 20 years professional experience. Member of Equity. Full performance insurance.",
      services: ["TV & Film Appearances", "Advertising Campaigns", "Photo Shoots", "Corporate Videos", "Premium Grottos", "Celebrity Events"],
      location: "Manchester",
      region: "North West",
      profileImageUrl: "https://images.unsplash.com/photo-1765870909790-f01a1bb2074d?w=600&fit=crop&q=80",
      galleryImages: [
        "https://images.unsplash.com/photo-1639264128236-78064efff737?w=800&fit=crop&q=80",
      ],
      youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      socialLinks: { website: "https://example.com", instagram: "https://instagram.com", twitter: "https://twitter.com" },
      pricingFrom: "£1,000",
      availableDates: "Year-round for media, November - December for events",
      contactEmail: "david@example.com",
      dbsChecked: true,
      realBeard: true,
      homeVisits: false,
      corporateEvents: true,
      schoolsNurseries: false,
      grottos: true,
      approved: true,
      featured: true,
    },
    {
      slug: "home-visit-santa-william",
      name: "William Ashworth",
      headline: "Home Visit Santa Specialist",
      type: "both",
      bio: "William specialises exclusively in personal home visits, creating intimate and unforgettable Christmas Eve and Christmas morning experiences for families. Each visit is carefully planned with parents in advance, with personalised details, named gift deliveries, and magical storytelling moments. William limits his bookings to ensure every family receives his full attention.",
      experience: "10 years of home visit experience. Over 2,000 family visits completed. Enhanced DBS checked. Paediatric first aid trained. Full public liability insurance.",
      services: ["Christmas Eve Home Visits", "Christmas Morning Visits", "Personalised Gift Deliveries", "Video Messages", "Breakfast with Santa"],
      location: "Bristol",
      region: "South West",
      profileImageUrl: "https://images.unsplash.com/photo-1543893419-fcc585654853?w=600&fit=crop&q=80",
      galleryImages: [
        "https://images.unsplash.com/photo-1511600173735-a896042389cf?w=800&fit=crop&q=80",
        "https://images.unsplash.com/photo-1603793303277-ed67787545e5?w=800&fit=crop&q=80",
      ],
      socialLinks: { facebook: "https://facebook.com", instagram: "https://instagram.com" },
      pricingFrom: "£300",
      availableDates: "December only (Christmas Eve and Christmas Morning)",
      contactEmail: "william@example.com",
      dbsChecked: true,
      realBeard: true,
      homeVisits: true,
      corporateEvents: false,
      schoolsNurseries: false,
      grottos: false,
      approved: true,
      featured: false,
    },
    {
      slug: "santa-voice-artist-tom",
      name: "Tom Bellingham",
      headline: "Professional Santa Voice Artist",
      type: "voice",
      bio: "Tom is a professional voice artist who specialises in authentic Father Christmas voice work. From personalised video messages and voicemail greetings to audiobook narration and advertising voiceovers, Tom's rich, warm baritone voice captures the essence of Santa Claus. He records from his professional home studio and can deliver high-quality audio within 24 hours.",
      experience: "Professional voice artist for 8 years. Clients include Amazon, Coca-Cola, and Royal Mail. Professional home studio with broadcast-quality equipment. Member of the Voice Artists Association.",
      services: ["Personalised Video Messages", "Voice Recordings", "Audiobook Narration", "Advertising Voiceovers", "Phone Greetings", "Live Virtual Appearances"],
      location: "Edinburgh",
      region: "Scotland",
      profileImageUrl: "https://images.unsplash.com/photo-1607715150652-6c4a5dd185e7?w=600&fit=crop&q=80",
      galleryImages: [],
      audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      socialLinks: { website: "https://example.com" },
      pricingFrom: "£75",
      availableDates: "Year-round",
      contactEmail: "tom@example.com",
      dbsChecked: false,
      realBeard: false,
      homeVisits: false,
      corporateEvents: true,
      schoolsNurseries: false,
      grottos: false,
      approved: true,
      featured: false,
    },
  ];

  await db.delete(santaListings);
  await db.insert(santaListings).values(sampleSantas);

  console.log(`Seeded ${sampleSantas.length} Santa profiles`);
  await pool.end();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
